name: Scheduled Ingest

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch: {}

jobs:
  call-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ingest endpoint
        env:
          PROD_URL: ${{ secrets.PROD_URL }}
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}
        run: |
          if [ -z "$PROD_URL" ] || [ -z "$INGEST_SECRET" ]; then
            echo "Missing PROD_URL or INGEST_SECRET GitHub secrets" >&2
            exit 1
          fi
          set -euo pipefail
          curl -sS -H "Authorization: Bearer $INGEST_SECRET" "$PROD_URL/api/ingest/uniswap?limit=50" | tee /dev/stderr

